version: '3'
services:
  red_book_scripts:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # 将自定义的Nginx配置文件挂载到容器中
      - ~/.ssl/lukas-bag.online_bundle.crt:/etc/nginx/lukas-bag.online_bundle.crt:ro
      - ~/.ssl/lukas-bag.online.key:/etc/nginx/lukas-bag.online.key:ro
    depends_on:
      - red_book_scripts

networks:
  app-network:
    driver: bridge