version: '3'
services:
  red_book_scripts:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # 将宿主机的80端口映射到容器的80端口
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # 将自定义的Nginx配置文件挂载到容器中
      - ~/.ssl:/www/server/nginx/conf:ro
    depends_on:
      - red_book_scripts

networks:
  app-network:
    driver: bridge